import Navbar from './Components/Navbar'
import './globals.css'
import { IBM_Plex_Mono } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
const ibm = IBM_Plex_Mono({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ibm.className}>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
